<?php

/**
 * @file
 * small module to copy specific nodes and clear old nodes so the database
 * does not get flodded.
 *
 * depents on regular cron runs
 */

/*
 * Implements hook_cron()
 * Controller to initiate copy
 */
function finalist_copy_node_cron() {

  // get last cron run or set to now when non exiting

}

/*
 * putting this in a hook_node_view so I can just refresh the page with a node
 * and also dpm does not seam to work in a hook_cron
 */
function finalist_copy_node_node_view($node, $view_mode, $langcode) {
  // TODO: cron interval to a variable that can be set in the admin interface

  // get last cron run for this else use last system cron time.
  $last_cron = variable_get('finalist_copy_node_cron', variable_get('cron_last'));

  dpm("Last cron run was: " . $last_cron);

  // one hour ago: ( minus 3600 seconds (60*60))
  $one_hour_ago = (time() - 3600);
  dpm("one hour ago: " . $one_hour_ago);

  if($last_cron <= $one_hour_ago) {
    // time to run cron again

    // give job to controller
    if(_finalist_copy_node_controller()) {
      // on succes update last cron run to now
      variable_set('finalist_copy_node_cron', time());
    }
  }

}
/*
 * logic component
 * Make sure previews cron is around 1 hour ago else skip this run
 *
 * select node function
 *
 * insert new nodes as other content type
 *
 * delete nodes from JSON crawled feed except the most recent ones or call
 * JOSN feed imedetly after.
 */
function _finalist_copy_node_controller() {
  $nodes = node_load_multiple(array(), array('type' => 'traject'));
  foreach ($nodes as $node) {
    dsm($node->nid);
  }
}


/*
 * function select nodes
 * select nodes where date is between now and now() -1 hour
 * and the most recent ones distinct by traject
 * returns node objects
 */
// disabled and moved to controller, makes no sense to create a function
// for one line of code.
// function finalist_copy_node_select_nodes(){
//   // select all traject nodes that are crawled using JSON feed.
//   // select * from node where type = "traject"


//   return $nodes;
// }

/*
 * function insert nodes
 * (node_save())
 */

/*
 * function delete nodes older then one hour
 */
