<?php

/**
 * @file
 * small module to copy specific nodes and clear old nodes so the database
 * does not get flodded.
 *
 * depents on regular cron runs
 */

/*
 * Implements hook_cron()
 * Controller to initiate copy
 */
function finalist_copy_node_cron() {

  // get last cron run or set to now when non exiting

}

/*
 * putting this in a hook_node_view so I can just refresh the page with a node
 * and also dpm does not seam to work in a hook_cron
 */
function finalist_copy_node_node_view($node, $view_mode, $langcode) {

  // get last cron run timestamp
  $last_cron = variable_get('cron_last');
  dpm("Last cron run was: " . $last_cron);

  // now:
  dpm(time());

  // one hour ago:

}
/*
 * logic component
 * Make sure previews cron is around 1 hour ago else skip this run
 *
 * select node function
 *
 * insert new nodes as other content type
 *
 * delete nodes from JSON crawled feed except the most recent ones or call
 * JOSN feed imedetly after.
 */

/*
 * function select nodes
 * select nodes where date is between now and now() -1 hour
 * and the most recent ones distinct by traject
 * returns node objects or array $nid
 */


/*
 * function insert nodes
 * (node_save())
 */

/*
 * function delete nodes older then one hour
 */
